### ISSUE TITLE
Inconsistent naming of 'USDT' for Bitfinex

### ISSUE THREAD

**Issue by yohplala** [bmoscon/cryptostore#100]
Hi,
Bitfinex is using `UST` instead of `USDT` usually found to name `Tether USD`.
This can be seen on Coingecko which is displaying pair names as it is given by the exchange (or so I think):
https://www.coingecko.com/en/exchanges/bitfinex

When pulling data, following naming works for `ETH`, but not for `BTC`.
```yaml
exchanges:
    BITFINEX:
        channel_timeouts:
            l2_book: 90
            trades: 90
        retries: 6
        trades: [ETH-UST]
        l2_book:
            symbols: [ETH-UST]
            book_delta: true
```

For BTC, this naming works.
```yaml
exchanges:
    BITFINEX:
        channel_timeouts:
            l2_book: 90
            trades: 90
        retries: 6
        trades: [BTC-USDT]
        l2_book:
            symbols: [BTC-USDT]
            book_delta: true
```

Shouldn't the naming of Tether USDT be consistent for all pairs?
