### ISSUE TITLE
OKEX does not distinguish futures/swap symbols correctly.

### ISSUE THREAD

**Issue by xiandong79** [bmoscon/cryptostore#106]
with latest cryptofeed version 1.5.1 and latest cryptostore:

```
    OKEX:
        retries: 30
        l2_book:
            symbols: [BTC-USDT, BTC-USD-200925, BTC-USD-SWAP]
            max_depth: 300
            book_delta: true
            book_interval: 600
        trades: [BTC-USDT, BTC-USD-200925, BTC-USD-SWAP, ETH-USDT]
```

```
2020-08-26 10:16:18,796 : ERROR : OKEX: Error: {'event': 'error', 'message': "Channel spot/depth_l2_tbt:BTC-USD-SWAP doesn't exist", 'errorCode': 30040}
2020-08-26 10:16:18,796 : ERROR : OKEX: Error: {'event': 'error', 'message': "Channel spot/depth_l2_tbt:BTC-USD-200925 doesn't exist", 'errorCode': 30040}
```
