### ISSUE TITLE
Support book_intervals on snapshots without deltas

### ISSUE THREAD

**Issue by mschneider** [bmoscon/cryptostore#117]
book_interval config variable is apparently ignored when not fetching book_deltas. I used the following config to store L2 snapshots. Looking at the code book_interval seems only considered in the `book_delta = True` code path.

```
    KRAKEN:
        l2_book:
            symbols: [BTC-USD, ETH-USD, ETH-BTC]
            max_depth: 16
            book_delta: false
            book_interval: 1000
```

Expected behavior: Store one order book snapshot per symbol per second
Current behavior: Store every order book change, stores more than 10 snapshots per symbol per second
