### ISSUE TITLE
Create a 'PARENT' exchange defining 'default' parameters for 'real' exchanges.

### ISSUE THREAD

**Issue by yohplala** [bmoscon/cryptostore#139]
**Is your feature request related to a problem? Please describe.**
To simplify option definitions for exchanges in configuration file, proposal is to be able to define a 'default' configuration that will be used by all listed exchanges in configuration files, and only new information defined individually per exchange will overwrite this 'default' configuration.
I see mostly 3 parameters that can be used as default: `channels`, `symbols` (pairs), `retries`

**Describe the solution you'd like**
The configuration file would then looks like this.
```yaml

exchanges:
  DEFAULT:
    symbols:[BTC/USDT, BTC/USD, ETH/USDT, ETH/USD]
    channels:
      trades
      l2_book:
        book_delta: true
    retries:-1
  BINANCE
  KRAKEN
  COINBASE:
    l2_book:
      symbols:[XRP/USD]
    retries:-1
```

If the exchanges has a dict structure, the information of the dict structure is retained (case of `COINBASE` above).
If the exchanges is simply a text value, the information from `PARENT`is retained.

What do you think?
