### ISSUE TITLE
Recent update to cryptofeed is causing error when applying cryptostore config

### ISSUE THREAD

**Issue by jeffneuen** [bmoscon/cryptostore#148]
Cryptostore does not appear to be completely compatible with changes introducted to cryptofeed/feedhandler in this commit: https://github.com/bmoscon/cryptofeed/commit/d81993957b1847879793c89957e32c8e35620d35#diff-9fad70d8501bc6736b79d842f38708a0cb13c76fd0dbcbc8793883cfb9eff685, at least the change on line 166, which was changed to be:  

```
self.feeds.append((_EXCHANGES[feed](config=self.config, **kwargs), timeout))
```
feedhandler is expecting a single value in self.config, and when it is passed a list containing tickers, it gives this error.
```
cryptostore_1  | Process Collector-1:1:
cryptostore_1  | Traceback (most recent call last):
cryptostore_1  |   File "/usr/local/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
cryptostore_1  |     self.run()
cryptostore_1  |   File "/cryptostore/collector.py", line 122, in run
cryptostore_1  |     fh.add_feed(self.exchange, timeout=timeout, max_depth=depth, snapshot_interval=snap_interval, book_interval=window, config={callback_type: self.exchange_config[callback_type]}, callbacks=cb)
cryptostore_1  |   File "/usr/local/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 166, in add_feed
cryptostore_1  |     self.feeds.append((_EXCHANGES[feed](config=self.config, **kwargs), timeout))
cryptostore_1  | TypeError: type object got multiple values for keyword argument 'config'
cryptostore_1  | Process Collector-1:2:
cryptostore_1  | Traceback (most recent call last):
cryptostore_1  |   File "/usr/local/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
cryptostore_1  |     self.run()
cryptostore_1  |   File "/cryptostore/collector.py", line 122, in run
cryptostore_1  |     fh.add_feed(self.exchange, timeout=timeout, max_depth=depth, snapshot_interval=snap_interval, book_interval=window, config={callback_type: self.exchange_config[callback_type]}, callbacks=cb)
cryptostore_1  |   File "/usr/local/lib/python3.7/site-packages/cryptofeed/feedhandler.py", line 166, in add_feed
cryptostore_1  |     self.feeds.append((_EXCHANGES[feed](config=self.config, **kwargs), timeout))
cryptostore_1  | TypeError: type object got multiple values for keyword argument 'config'
```
Running using docker-compose. config-docker.yaml is below. Running on ubuntu 20.04, docker and docker-compose both installed from docker as opposed to ubuntu repos.

```
# Cryptostore sample config file for Docker

cache: redis

redis:
    ip: redisdb
    port: 6379
    del_after_read: true
    start_flush: true
    socket: null

exchanges:
    COINBASE:
        l3_book:
            symbols: [BTC-USD]
            book_delta: true
            book_interval: 10000
        trades: [BTC-USD]

storage: [parquet]
#arctic: mongodb://mongo:27017

storage_interval: 60
storage_retries: 5
storage_retry_wait: 30

#plugins:
#  backfill:
#    module: [cryptostore.plugin.backfill, Backfill]
#    config: config.yaml

#backfill:
#    COINBASE:
#        BTC-USD:
#            start: '2017-01-01'
```
