### ISSUE TITLE
[Parquet] ValueError: Table schema does not match schema used to create file

### ISSUE THREAD

**Issue by dirtyValera** [bmoscon/cryptostore#154]
**Describe the bug**
I'm running cryptostore to get l2/trades/ticker feed from Binance for multiple pairs. It works fine first few minutes, but then I get

'2021-02-04 11:01:48,993 : ERROR : Aggregator running on PID 56410 died due to exception
...
ValueError: Table schema does not match schema used to create file:
...
'
  
**To Reproduce**
I'm using kafka as a medium, storing data locally on disk in parquet files

Config: https://pastebin.com/fpQQDm0r

Trace: https://pastebin.com/9T3wHTTW

**Operating System:**
Running locally on Mac

**Cryptofeed Version**
I'm building off master on github

**Comment by dirtyValera** [comment]
Looks like 'amount' in schema is double while 'amount' in file is int64. Why is it so?

**Comment by dirtyValera** [comment]
Got another error like this, with a different field now ('size'), same type mismatch: double vs int64
Trace: https://pastebin.com/630QDAHd

**Comment by yohplala** [comment]
Hello @dirtyValera  hi @bmoscon 
I had a quick look at the source and I possibly have some clue.
`size` and `amount` are 2 columns I am not initializing when creating the parquet files, they are inferred.

You have set 60s storage interval, and on your `ETH`-based paris, I would not be surprised there is no trade for 60s.
```python
      - QTUM-ETH
      - EOS-ETH
      - SNT-ETH
      - BNT-ETH
```

Like BNT for instant or SNT. (I don't even know what SNT is :))
So my guess is that there are very few trades each time a parquet file is written (maybe only one), and that at this time, it can happen that the `amount` or `size` is an `int`.
I think the reversed message is also possible.

I have not time to work on this.
Please, on your side, can you confirm:
- for more traded pairs, this error message do not show up (take a BTC-USDT pair, you will be fine :))
As a workaround for the time being, if you only have these pairs, you can switch off `append_counter` and keep a `storage_interval` to 300. Fingers crossed thhat you will not run out of memory...
`ETH-BTC`, and `BNB-BTC` l2 book order will however consume some.
If you have at least 4Go of RAM, it should be ok.
If you have less than 2Go, ... really not sure.

**Comment by emiliobasualdo** [comment]
Same error here. Using Redis & Binance.
```
# Cryptostore sample config file

cache: redis
redis:
    ip: '127.0.0.1'
    port: 6379
    socket: null
    del_after_read: true
    retention_time: null
    start_flush: true

binance_symbols: &binance_symbols [BTC-USDT, ETH-USDT, DOT-USDT, EGLD-USDT, XLM-USDT, BNB-USDT, ADA-USDT, LTC-USDT, NEO-USDT, ATOM-USDT, IOTA-USDT, SAND-USDT, COCOS-USDT, ALGO-USDT, THETA-USDT, DASH-USDT, DUSK-USDT, BTC-EUR, ETH-EUR, DOT-EUR, XLM-EUR, BNB-EUR, ADA-EUR, LTC-EUR, BTC-AUD, ETH-AUD, BNB-AUD, BTC-BRL, ETH-BRL, BNB-BRL, LTC-BRL, BTC-RUB, ETH-RUB, BNB-RUB, LTC-RUB, EUR-USDT, AUD-USDT, USDT-BRL, USDT-RUB]
exchanges:
    BINANCE:
        retries: -1
        l2_book:
            symbols: *binance_symbols
            max_depth: 500
            book_delta: true
        ticker: *binance_symbols


storage: [parquet]
storage_retries: 5
storage_retry_wait: 30
storage_interval: 60
#storage: [arctic]
#arctic: mongodb://127.0.0.1
parquet:
    del_file: true
    append_counter: 4
    path: ./
    file_format: [timestamp]
    prefix_date: false
    compression:
        codec: BROTLI
        level: 6
    S3:
        endpoint: null
        key_id: xxxxxx
        secret: xxxxx
        bucket: xxxxx
        prefix: null
```
