### ISSUE TITLE
Provide some examples of docker-compose.yml files

### ISSUE THREAD

**Issue by c0indev3l** [bmoscon/cryptostore#225]
Hello,

I wonder if some examples of docker-compose.yml files should be given to quickstart a simple cryptostore.

Kind regards

**Comment by c0indev3l** [comment]
I tried the TCP example with

```yaml
version: "3.3"
services:
  cryptostore2tty:
    image: ghcr.io/bmoscon/cryptostore:latest
    environment:
      - EXCHANGE=COINBASE
      - CHANNELS=trades
      - SYMBOLS=BTC-USDT
      - BACKEND=TCP
      - HOST=tcp://127.0.0.1
      - PORT=8080
```

`docker compose up`

and on an other console

`python tcp.py`

but nothing appears
