### ISSUE TITLE
Book are not stored in QuestDB but are displayed on TTY

### ISSUE THREAD

**Issue by c0indev3l** [bmoscon/cryptostore#233]
Hello,

I'm using a Docker Compose file like so

```
version: "3.3"
services:
  cs2questdb_book:
    image: ghcr.io/bmoscon/cryptostore:latest
    container_name: cs2questdb_book
    environment:
      - EXCHANGE=BINANCE
      - SYMBOLS=BTC-USDT,ETH-USDT,BNB-USDT,SOL-USDT,ADA-USDT
      - CHANNELS=l2_book
      - BACKEND=QUEST # TTY
      - HOST=${HOST}
      - PORT=${PORT}
    restart: unless-stopped
    networks:
      - web

networks:
  web:
    external: true
```

When I set backend to TTY I see

    cs2questdb_book  | 2024-03-19 21:15:51 - exchange: BINANCE symbol: ADA-USDT book: <order_book.OrderBook object at 0x7f271e4ea870> timestamp: 1710882951.471

but when I set BACKEND to QUEST, book are not stored into book-BINANCE table.

On the other side, when I set

    CHANNELS=candles,trades,ticker

these data are correctly stored into database.

I've no idea why it's not working for L2 book.

I entered into container but `feedhandler.log` is empty.

Any idea how to overcome that?

Thanks for your project
