### ISSUE TITLE
Message length too long, dropping. for BITMEX using cryptostore 0.1.0

### ISSUE THREAD

**Issue by xiandong79** [bmoscon/cryptostore#24]
2019-07-26 14:16:46,769 : ERROR : BITMEX: Error message from exchange: {'status': 400, 'error': 'Failed to decode incoming data: Message length too long, dropping. Please see the documentation at https://www.bitmex.com/app/wsAPI.', 'meta': {}}

with following in config.yaml:
```
cache: redis

exchanges:
    BITMEX:
        l2_book: [XBTUSD, ETHUSD, XRPU19, BCHU19, ADAU19, EOSU19, TRXU19, XBTU19, XBTZ19, ETHU19, LTCU19]
        l3_book: [XBTUSD, ETHUSD]
        trades: [XBTUSD, ETHUSD, XRPU19, BCHU19, ADAU19, EOSU19, TRXU19, XBTU19, XBTZ19, ETHU19, LTCU19]

storage: [influx, parquet]
```

**cryptostore 0.1.0
cryptofeed 1.0.0**
