### ISSUE TITLE
Bitmex l2_orderbook not doing book_delta

### ISSUE THREAD

**Issue by e-mulville** [bmoscon/cryptostore#29]
Subscribing to the order books in config.yml like so:
```
exchanges:
    BITMEX:
        l2_book: [XBTUSD, ETHUSD]
        trades: [XBTUSD, ETHUSD]
    COINBASE:
        l2_book: [BTC-USD, ETH-USD]
        trades: [BTC-USD, ETH-USD]
    BITFINEX:
        l2_book: [BTC-USD, ETH-USD]
        trades: [BTC-USD, ETH-USD]
```

With `book_depth: null` and `book_delta: True` then picking up the updates through the zmq pass through I am finding that while Coinbase and Bitmex are giving deltas Bitmex seems to be giving 10 levels of the orderbook each time, like so:

{'feed': 'BITMEX', 'pair': 'XBTUSD', 'delta': False, 'data': {'timestamp': 1564677658.873, 'bid': {'10070': '41090', '10069.5': '5724', '10069': '224', '10068.5': '28247', '10068': '423966', '10067.5': '56534', '10067': '509', '10066.5': '12933', '10066': '1957', '10065.5': '6534'}, 'ask': {'10070.5': '1256387', '10071': '11214', '10071.5': '20090', '10072': '7752', '10072.5': '13704', '10073': '13979', '10073.5': '26827', '10074': '31755', '10074.5': '33530', '10075': '44829'}}}

From the same feed for Coinbase and Bitfinex I am getting:

{'feed': 'COINBASE', 'pair': 'BTC-USD', 'delta': True, 'data': {'timestamp': 1564677661.0444381, 'bid': {'10043.01000000': '0'}, 'ask': {}}}
 {'feed': 'BITFINEX', 'pair': 'ETH-USD', 'delta': True, 'data': {'timestamp': 1564677661.065808, 'bid': {'214.29': '0'}, 'ask': {}}}
