### ISSUE TITLE
Deribit OI 

### ISSUE THREAD

**Issue by bonald** [bmoscon/cryptostore#62]
No error message when running deribit with open_interest
Mesearuement is created by cryptostore fine.
Redis had the data but nothing gets written to influxdb measurement.

30|cryptostore-DERIBIT  | 2020-03-01 21:23:26,029 : INFO : Reading DERIBIT-open_interest-ETH-PERPETUAL
30|cryptostore-DERIBIT  | 2020-03-01 21:23:26,029 : INFO : open_interest-DERIBIT-ETH-PERPETUAL: Read 1 messages from Redis
30|cryptostore-DERIBIT  | 2020-03-01 21:23:26,031 : INFO : open_interest-DERIBIT-ETH-PERPETUAL: Removed no Redis entries
30|cryptostore-DERIBIT  | 2020-03-01 21:23:26,031 : INFO : Write Complete DERIBIT-open_interest-ETH-PERPETUAL

**Comment by bmoscon** [comment]
I'll see if I can reproduce it and let you know

**Comment by bmoscon** [comment]
I'd need to see your config @bonald - I just tested this and worked just fine and I confirmed data was in Influx. I'll also need to see the query you're running to check influx

**Comment by bonald** [comment]
select * from open_interest-DERIBIT

Trades are fine and funding too...
I got it working with cryptofeed also...
 
Wondering what's wrong with my setup if you have it working on your side.

```
exchanges:
    DERIBIT:
        retries: -1
#        l2_book:
#            symbols: [BTC-PERPETUAL, ETH-PERPETUAL]
#            book_delta: true
#            book_interval: 1000
        trades: [BTC-PERPETUAL, ETH-PERPETUAL]
#      ticker: [BTC-PERPETUAL, ETH-PERPETUAL]
        funding: [BTC-PERPETUAL, ETH-PERPETUAL]
        open_interest: [BTC-PERPETUAL, ETH-PERPETUAL]
```
