### ISSUE TITLE
zmq not receive msg

### ISSUE THREAD

**Issue by xiandong79** [bmoscon/cryptostore#65]
```
cache: redis
redis:
    ip: '127.0.0.1'
    port: 6379
    socket: null
    del_after_read: true
    retention_time: null
    start_flush: true
exchanges:
    BITMEX:
        retries: 30
        l2_book:
            symbols: [XBTUSD]
            max_depth: 300
            book_delta: true
            book_interval: 600
        trades: [XBTUSD]
storage: [influx]
pass_through:
    type: zmq
    host: '127.0.0.1'
    port: 5678
influx:
    host: 'http://127.0.0.1:8086'
    db: market_data
    create: true
storage_interval: 60
```

zmq not receive msg

test by `test_zmq.py`

```
import zmq
# Socket to talk to server
context = zmq.Context()
socket = context.socket(zmq.SUB)
socket.connect("tcp://127.0.0.1:5678")
socket.subscribe("")  # Subscribe to all topics
while 1:
    string = socket.recv_string()
    print(string)
```
