### ISSUE TITLE
Collector does not connect to redis using unix sockets

### ISSUE THREAD

**Issue by feralcab** [bmoscon/cryptostore#78]
Collector does not connect to redis using unix sockets, when configured to do so. 

This sample configuration still results in a tcp connection to redis instead of a unix socket connection.  Redis is configured to accept unix socket connections, and the socket file is created with the correct permissions.

```
cache: redis
redis:
    ip: '127.0.0.1'
    port: 6379
    socket: '/usr/local/var/run/redis/redis.sock'
    del_after_read: true
    retention_time: 90
    start_flush: true
```

**Comment by bmoscon** [comment]
try setting ip and port to null

```
cache: redis
redis:
    ip: null
    port: null
    socket: '/usr/local/var/run/redis/redis.sock'
    del_after_read: true
    retention_time: 90
    start_flush: true
```

It should work then
