### ISSUE TITLE
Unable to retrieve data from Deribit

### ISSUE THREAD

**Issue by 0xd1ce** [bmoscon/cryptostore#83]
I'm trying to retrieve data for BTC-PERPETUAL from Deribit. I'm new the project, so it's likely that I'm just configuring Cryptostore incorrectly.

The config file I'm using is:
```
# Cryptostore sample config file

# Redis or Kafka are required. They are used to batch updates from cryptofeed and the storage medium of choice
#
# del_after_read: (redis only) toggles the removal of data from redis after it has been processed with cryptostore.
# retention_time: (redis only) if data removal is enabled (via del_after_read) will allow retention of data in redis for N seconds.
# socket: (redis only) allows redis connections via a unix domain socket
# start_flush: toggles if redis/kafka should be flushed at the start. Primarily for debugging, it will flush ALL of redis/kafka
cache: redis

kafka:
    # ip/port are for the bootstrap server
    #    ip: '127.0.0.1'
    #port: 9092
    #start_flush: true
redis:
    ip: '127.0.0.1'
    port: 6379
    socket: null
    del_after_read: true
    retention_time: null
    start_flush: true

# Data sources and data types configured under exchanges. Exchange names follow the naming scheme in cryptofeed (they
# must be capitalized) and only exchanges supported by cryptofeed are supported.
# data types follow cryptofeed definitions, see defines.py in cryptofeed for more details, common ones are
# trades, l2_book, l3_book, funding, ticker, and open_interest
# Trading pairs for all exchanges (except BitMEX) follow the currency-quote format
#
# max_depth controls the size of the book to return. The top N levels will be returned, only when those N levels
# have changed.
# book_delta enables book deltas (snapshot, then only deltas are delivered). Snapshops are delivered
# every book_interval updates. book_interval defaults to 1000 if not specified
#
# Retries are the number of times the connection to the exchange will be retried before exiting. -1 is infinity.
# Using a retry of -1 with a bug in your config can lead to bans by exchanges
#
# Channel timeouts are channel specific and control how long a channel can go with no messages before declaring the connection
# dead. Cryptofeed will restart the connection if no message is received in this time period. Default is 120 seconds. -1 means no timeout.

# Attempt at defining to collect Deribit data
exchanges:
        deribit:
                retries: 10
                trades: [BTC-PERPETUAL]
                ticker: [BTC-PERPETUAL]
                volume: [BTC-PEPETUAL]
                funding: [BTC-PERPETUAL]
                trades_swap: [BTC-PERPETUAL]
                ticker_swap: [BTC-PERPETUAL]
                open_interest: [BTC-PERPETUAL]

# Where to store the data. Currently arctic, influx, elastic, and parquet are supported. More than one can be enabled
storage: [arctic]

# Configurable passthrough for data - data will be sent in realtime (no aggregation in redis).
# To disable, remove
#pass_through:
#    type: zmq
#    host: '127.0.0.1'
#    port: 5678


#elastic:
#    host: 'http://127.0.0.1:9200'
#    user: null
#    token: null
#    shards: 10
#    replicas: 0
#    refresh_interval: '30s'

#influx:
#    host: 'http://127.0.0.1:8086'
#    db: example
#    create: true

# Parquet specific options. Parquet will default to storing the data on disk unless these are specified
parquet:
    # if storing the data to an external source (like S3) toggle this to enable the removal of the local file after
    # writing to external store
    del_file: true
    # File name format, as a list of arguments. Default is <exchange>-<data_type>-<pair>-<timestamp>.parquet, which would be exchange, data_type, pair, timestamp
    # Can specify any combination exchange, data_type, pair, and timestamp
    # timestamp MUST be present.
    # examples:
    #    pair,timestamp
    #    timestamp
    #    timestamp,exchange
    #    etc
    file_format: [exchange, pair, data_type, timestamp]
    # Path controls where the file is written (if not using S3/GC) If null, will write to CWD. Must be absolute path
    path: null


    S3:
        # endpoint allows you to override the write endpoint and write to other provicers that have the same API interface
        # If key_id/secret are NULL boto will default to using ENV vars or credentials file
        # prefix: a prefix to append to the default data path
        endpoint: null
        key_id: null
        secret: null
        bucket: null
        prefix: null
    GCS:
        # path to service account key, if null will default to using env vars or auth tokens
        # on GCE node
        # prefix: a prefix to append to the default data path
        service_account: null
        bucket: null
        prefix: null

# arctic specific configuration options - the mongo URL
arctic: mongodb://127.0.0.1

# Data batching window, in seconds, or optionally a time interval: M(inutely), H(ourly), D(aily).
# These intervals will require that you have enough memory available to redis (and python) to hold this amount of data.
# String intervals can be combined with numbers, eg 2H is 2 hours, 5M is 5 minutes, etc.
storage_interval: 60


# Cryptostore Plugin Interface
plugins:
    backfill:
        # The import path, and class name
        # from cryptostore.plugin.backfill import Backfill
        module: [cryptostore.plugin.backfill, Backfill]
        # Config path, config can be added to this file, or in a separate config
        # backfill does not use a dynamic config, so its fine to put its config here
        config: config.yaml

# If configured, backfill will run in a separate process and
# backfill trade data from earliest data (in storage) up to `start` (inclusive).
#backfill:
#    COINBASE:
#        BTC-USD:
#            start: '2017-01-01'
```

The results I get, which will continue indefinitely are:
```
2020-05-15 16:21:27,526 : INFO : Reading deribit-trades-BTC-PERPETUAL
2020-05-15 16:21:27,526 : INFO : No data for deribit-trades-BTC-PERPETUAL
2020-05-15 16:21:27,526 : INFO : Reading deribit-ticker-BTC-PERPETUAL
2020-05-15 16:21:27,527 : INFO : No data for deribit-ticker-BTC-PERPETUAL
2020-05-15 16:21:27,527 : INFO : Reading deribit-volume-BTC-PEPETUAL
2020-05-15 16:21:27,527 : INFO : No data for deribit-volume-BTC-PEPETUAL
2020-05-15 16:21:27,527 : INFO : Reading deribit-funding-BTC-PERPETUAL
2020-05-15 16:21:27,527 : INFO : No data for deribit-funding-BTC-PERPETUAL
2020-05-15 16:21:27,527 : INFO : Reading deribit-trades_swap-BTC-PERPETUAL
2020-05-15 16:21:27,528 : INFO : No data for deribit-trades_swap-BTC-PERPETUAL
2020-05-15 16:21:27,528 : INFO : Reading deribit-ticker_swap-BTC-PERPETUAL
2020-05-15 16:21:27,528 : INFO : No data for deribit-ticker_swap-BTC-PERPETUAL
2020-05-15 16:21:27,528 : INFO : Reading deribit-open_interest-BTC-PERPETUAL
2020-05-15 16:21:27,528 : INFO : No data for deribit-open_interest-BTC-PERPETUAL
2020-05-15 16:22:27,451 : INFO : Reading deribit-trades-BTC-PERPETUAL
2020-05-15 16:22:27,451 : INFO : No data for deribit-trades-BTC-PERPETUAL
2020-05-15 16:22:27,451 : INFO : Reading deribit-ticker-BTC-PERPETUAL
2020-05-15 16:22:27,452 : INFO : No data for deribit-ticker-BTC-PERPETUAL
2020-05-15 16:22:27,452 : INFO : Reading deribit-volume-BTC-PEPETUAL
2020-05-15 16:22:27,452 : INFO : No data for deribit-volume-BTC-PEPETUAL
2020-05-15 16:22:27,452 : INFO : Reading deribit-funding-BTC-PERPETUAL
2020-05-15 16:22:27,452 : INFO : No data for deribit-funding-BTC-PERPETUAL
2020-05-15 16:22:27,452 : INFO : Reading deribit-trades_swap-BTC-PERPETUAL
2020-05-15 16:22:27,453 : INFO : No data for deribit-trades_swap-BTC-PERPETUAL
2020-05-15 16:22:27,453 : INFO : Reading deribit-ticker_swap-BTC-PERPETUAL
2020-05-15 16:22:27,453 : INFO : No data for deribit-ticker_swap-BTC-PERPETUAL
2020-05-15 16:22:27,453 : INFO : Reading deribit-open_interest-BTC-PERPETUAL
2020-05-15 16:22:27,453 : INFO : No data for deribit-open_interest-BTC-PERPETUAL
```

I had a look at  the part of cryptofeed responsible for handling the Deribit API and found this on lines 39-41 of deribit.py (link below):
```
@staticmethod
    def get_instruments_info():
        r = requests.get(
            'https://www.deribit.com/api/v2/public/getinstruments?expired=false').json()
        return r
```
https://github.com/bmoscon/cryptofeed/blob/2e07d24ef638cbff4adbedf40f7d8a70728bee6a/cryptofeed/exchange/deribit.py#L42

If i try and manually make this request within a python terminal I get:
```
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.deribit.com', port=443): Max retries exceeded with url: /api/v2/public/getinstruments?expired=false (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fb65a832fd0>: Failed to establish a new connection: [Errno 111] Connection refused')
```
Changing the endpoint to use test.deribit.com however will work and return the available instruments. Could this be related to the issues I'm having?

I'm not the most experienced coder (nor have a deep understanding of the intricacies of both cryptofeed and cryptostore so please forgive any misunderstanding. Just looking for a solution.

Any help would be much appreciated. This project looks awesome btw.
