### ISSUE TITLE
Error While Reading from socket

### ISSUE THREAD

**Issue by DannyMartens** [bmoscon/cryptostore#99]
Hi, 

Using this config:

```
cache: redis

kafka:
    # ip/port are for the bootstrap server
    ip: '127.0.0.1'
    port: 9092
    start_flush: true
redis:
    ip: '127.0.0.1'
    port: 6379
    socket: null
    del_after_read: true
    retention_time: null
    start_flush: true

exchanges:
    BITMEX:
        channel_timeouts:
            l2_book: 30
            trades: 120
            ticker: 120
            funding: -1
        retries: -1
        l2_book:
            symbols: [XBTUSD]
            max_depth: 10
            book_delta: true
            book_interval: 100000
        trades: [XBTUSD]
        ticker: [XBTUSD]
        funding: [XBTUSD]
    COINBASE:
        retries: -1
        l3_book:
            symbols: [BTC-USD]
            book_delta: true
            book_interval: 100000
        trades: [BTC-USD, ETH-USD, ETH-BTC]
        ticker: [BTC-USD]

# Where to store the data. Currently arctic, influx, elastic, and parquet are supported. More than one can be enabled
storage: [arctic]

# arctic specific configuration options - the mongo URL
arctic: mongodb://127.0.0.1

storage_interval: 60
```

gives this error:
![image](https://user-images.githubusercontent.com/37220423/90574019-76e37080-e17d-11ea-87c8-99a94023e462.png)

I may be missing something, but any help would be greatly appreciated
